### ISSUE TITLE
Frame number issue

### ISSUE THREAD

**Issue by Eddie0131** [AIFARMS/AVAT#64]
The annotated frame should be 0, 15, 30….. But they were displayed at 1,16, 31….which does not match with the polygon. Here is the sample video and annotation file for debugging.https://uofi.box.com/s/b23hx6s0vlw6rc78gun2qurdahwgelog

**Comment by pradeepsen99** [comment]
This issue is in regards to an older version of AVAT - closing due to new version changes.
